### ISSUE TITLE
Package version 0.11.14

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ruamel_yaml-feedstock#2]
Appears there is a `0.11.14` release for `ruamel_yaml` that is in `defaults`. Would be good if we could package it here.

However, we seem to be missing a tag that we can use. 😕 Could we please get a tag when you have a chance, @kalefranz? Will also raise this on the [repo](https://bitbucket.org/kalefranz/yaml) as well.

**Comment by jakirkham** [comment]
Opened upstream issue ( https://bitbucket.org/kalefranz/yaml/issues/1 ).

**Comment by kalefranz** [comment]
Actually I wasn't planning on maintaining anything in that fork.  The recipe we're using in the anaconda repo has all the patches.

https://github.com/ContinuumIO/anaconda-recipes/tree/master/ruamel_yaml

**Comment by jakirkham** [comment]
I see. So this should move towards patching here too? Are the releases otherwise identical to ( https://bitbucket.org/ruamel/yaml ) excepting these patches?

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/ruamel_yaml-feedstock/pull/3 ).
