### ISSUE TITLE
Repository https://bitbucket.org/ruamel/yaml has been deleted

### ISSUE THREAD

**Issue by beenje** [conda-forge/ruamel_yaml-feedstock#64]
Issue:

The repository https://bitbucket.org/ruamel/yaml has been deleted:

> Our apologies, but the repository "ruamel/yaml" has been deleted.
> It now lives at https://sourceforge.net/p/ruamel-yaml.

The recipe can't be built anymore. The url should be updated.

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by isuruf** [comment]
@jakirkham, what do you want core to do?

**Comment by scopatz** [comment]
Seems like this is an easy PR.

**Comment by jamesmyatt** [comment]
Given what it says in https://github.com/conda-forge/ruamel.yaml-feedstock/issues/7 (and https://github.com/conda-forge/ruamel_yaml-feedstock/issues/1), is this the right resolution for this issue? Should it actually be tracking some Anaconda Inc repo?

**Comment by jamesmyatt** [comment]
Fixed by #66
