### ISSUE TITLE
cannot call class __init__() function

### ISSUE THREAD

**Issue by 0wenwu** [conda-forge/ruamel_yaml-feedstock#86]
use ruamel.yaml to load yaml file into python class, and found the  `__init__()` function can not be called.
So if the fields are not all written in yaml file, the unwritten fields can not be reflected into the python class.
For example.
```
class user:
     def __init__(self,name,age,sex='man'):
          self.name=name
          self.age=age
          self.sex=sex

```
yaml file:
```
user1:  !user
      name: 'name'
      age: 18
```

In this example, load the yaml file into python class and the instance user1 does not have the attribute sex.
It will bring some problems in the following calculation processes.

**Comment by isuruf** [comment]
This is not an issue tracker for ruamel_yaml. See https://sourceforge.net/p/ruamel-yaml/tickets/
